name: Packwerk checks
on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - '*'
jobs:
  packwerk:
    name: "Packwerk Validate"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
    - name: Validates packages
      run: |
        sudo apt-get -yqq install libpq-dev
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec packwerk validate
