name: Typescript Checks
on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - '*'
jobs:
  typescript_check:
    name: "Typescript check"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Setup node'
      uses: actions/setup-node@v2
      with:
        node-version: '14.18.3'
    - name: "Yarn install"
      run: |
        sudo apt-get -yqq install libpq-dev
        yarn install
    - name: "Run tsc"
      run: ./node_modules/.bin/tsc
